#!/bin/bash

# Needs:
# - ssh and scp (openssh)
# - convert (imagemagick)
# - pdftk (pdftk)
# - rsvg-convert (optional, to avoid rasterizing of lines)

if [[ $# -eq 0 ]] ; then
    echo "Usage: ./exportNotebook (Partial)NotebookName AdditionalrM2svgArguments"
    echo "You can additionally append the -c argument for coloured annotations."
    exit 0
fi

# Check if ssh configuration for "remarkable" exists
grep -Fxq "host remarkable" ~/.ssh/config
if [ $? -eq 0 ]; then
    SSH_IP="root@remarkable"
else
    SSH_IP="root@10.11.99.1"
fi

# Getting the notebook prefix (Newest notebook matching the name)
id=$(ssh ${SSH_IP} "ls -rt .local/share/remarkable/xochitl/*.metadata | xargs fgrep -l $1" | tail -n1 | cut -d. -f1,2)

test -z "$id" && exit 1

tmpfolder=$(mktemp -d)

# Getting notebook data
scp -q ${SSH_IP}:"${id}".{lines,pagedata,metadata} "${tmpfolder}"/

# Copy underyling document pdf if it exists
ssh -q ${SSH_IP} "[[ -f "${id}.pdf" ]]" && scp -q ${SSH_IP}:"${id}.pdf" "${tmpfolder}"

# Fix for single page notebooks with no template (empty pagedata file by default)
if [ ! -s "${tmpfolder}"/*.pagedata ]
then
  echo "Blank" > "${tmpfolder}"/*.pagedata
fi

# Fix empty lines in pagedata files
sed -i -e "s/^[[:blank:]]*$/Blank/" "${tmpfolder}"/*.pagedata

filename=$(grep -F  '"visibleName"' "${tmpfolder}"/*.metadata | cut -d: -f2- | grep -o '"[^"]*"')
echo "Exporting notebook ${filename} ($(wc -l "${tmpfolder}"/*.pagedata | cut -d\  -f1) pages)"

if [ -f "${tmpfolder}"/*.pdf ]
then
    echo "Found underlying document PDF, using as background."
    cp "${tmpfolder}/"*.pdf "${tmpfolder}/background.pdf"
else
    # Getting template files
    sort -u "${tmpfolder}"/*.pagedata | while read -r tpl; do
    scp -q ${SSH_IP}:"'/usr/share/remarkable/templates/${tpl}.png'" "${tmpfolder}"/
    done

    # Generate a PDF file out of the templates
    sed -e "s|^|\"${tmpfolder}\"/\"|" -e 's|$|.png"|' "${tmpfolder}"/*.pagedata | tr '\n' ' ' | sed -e "s|$|-transparent white \"${tmpfolder}\"/background.pdf|" | xargs convert
fi

# Extract annotations and create a PDF
rM2svg --input "${tmpfolder}"/*.lines --output "${tmpfolder}/foreground" $2

if command -v "rsvg-convert" > /dev/null
then
    rsvg-convert -a -f pdf "${tmpfolder}"/foreground*.svg -o "${tmpfolder}"/foreground.pdf
else
    convert -density 100 "${tmpfolder}"/foreground*.svg -transparent white "${tmpfolder}"/foreground.pdf
fi

# Strip .pdf suffix if it already exists (document vs. notebook)
filename=$(basename -s .pdf ${filename//\"/})

# Use multistamp instead of multibackground to preserve transparency
pdftk "${tmpfolder}"/foreground.pdf multistamp "${tmpfolder}"/background.pdf output "${filename}.pdf"

filesize=$(ls -la "${filename}.pdf" | awk '{print $5}' | numfmt --to=iec-i --suffix=B --format="%.3f")
echo "Written ${filesize} to ${filename}.pdf"

rm -Rf "${tmpfolder}"
